/** Maps PH topic names to category page slugs. */
export const TOPIC_TO_CATEGORY: Record<string, string> = {
  'Artificial Intelligence': 'artificial-intelligence',
  'AI': 'artificial-intelligence',
  'Machine Learning': 'artificial-intelligence',
  'Developer Tools': 'developer-tools',
  'Dev Tools': 'developer-tools',
  'GitHub': 'developer-tools',
  'Vibe coding': 'developer-tools',
  'Open Source': 'open-source',
  'Productivity': 'productivity',
  'Marketing': 'marketing',
  'Growth Hacking': 'marketing',
  'SEO': 'marketing',
  'Sales': 'sales',
  'CRM': 'sales',
  'Customer Success': 'saas',
  'SaaS': 'saas',
  'B2B': 'saas',
  'Analytics': 'analytics',
  'Finance': 'finance',
  'Fintech': 'finance',
  'Crypto': 'web3',
  'Web3': 'web3',
  'Blockchain': 'web3',
  'Health': 'health-wellness',
  'Wellness': 'health-wellness',
  'Fitness': 'health-wellness',
  'Education': 'education',
  'Learning': 'education',
  'No-code': 'no-code',
  'No Code': 'no-code',
  'Mobile': 'mobile',
  'iOS': 'mobile',
  'Android': 'mobile',
  'Chrome Extensions': 'browser-extensions',
  'Browser Extensions': 'browser-extensions',
  'Security': 'security',
  'Privacy': 'security',
  'Social': 'social',
  'Community': 'social',
  'E-commerce': 'ecommerce',
  'Ecommerce': 'ecommerce',
  'Infrastructure': 'infrastructure',
  'DevOps': 'infrastructure',
  'Design': 'design-tools',
  'Design Tools': 'design-tools',
  'UI': 'design-tools',
  'UX': 'design-tools',
};

export function topicCategorySlug(topic: string): string | null {
  return TOPIC_TO_CATEGORY[topic] ?? null;
}
